//! Embedded static assets — CSS and JS.
//!
//! Asset URLs include a content hash for cache busting:
//! `/b/static/app-{hash}.css` and `/b/static/htmx-{hash}.min.js`

use std::sync::{LazyLock, OnceLock};

use crate::routing::STATIC_PREFIX;

const TOKENS_CSS: &str = include_str!("assets/tokens.css");
const BASE_CSS: &str = include_str!("assets/base.css");
const COMPONENTS_CSS: &str = include_str!("assets/components.css");
const LAYOUT_CSS: &str = include_str!("assets/layout.css");
const CHARTS_CSS: &str = include_str!("assets/charts.css");

/// `buildRequest`/`toolOptions` — the request-building and tool-option-shaping
/// logic shared by `webmcp.js` and the `/b/dev` page's `dev.js`. A fragment,
/// not a script: no IIFE, no `'use strict'`. Never served on its own — always
/// composed into a caller's IIFE via [`compose_webmcp_script`].
const WEBMCP_CORE: &str = include_str!("assets/webmcp-core.js");

/// Wraps `WEBMCP_CORE` and a caller-specific `tail` in one IIFE, so the
/// composed script reads exactly as if it had been written in one file:
/// `(function () { 'use strict'; <core> <tail> })();`
///
/// `pub(crate)` because the second caller is a block's own asset module
/// (`blocks::dev::assets`), not this one: a tail authored anywhere in the
/// crate composes through the same function, so there is exactly one
/// definition of what "a WebMCP script" is on the wire.
pub(crate) fn compose_webmcp_script(tail: &'static str) -> String {
    format!("(function () {{\n  'use strict';\n{WEBMCP_CORE}\n{tail}\n}})();\n")
}

/// Itim font binaries, sourced from `impresspress/site-kit`'s `/fonts/` mirror
/// and committed here so every impresspress deployment ships its own glyphs
/// (no cross-origin runtime dependency, no `https://impresspress.org/fonts/` 404).
const ITIM_LATIN_WOFF2: &[u8] = include_bytes!("assets/fonts/itim-latin.woff2");
const ITIM_LATIN_EXT_WOFF2: &[u8] = include_bytes!("assets/fonts/itim-latin-ext.woff2");

/// Square Impresspress mark used as the sidebar/login icon. Bundled locally so
/// the admin renders correctly without internet (the previous default pointed
/// at `https://impresspress.org/images/logo.png` which 404s offline).
///
/// The mark is real pixel art — 32x32 art-pixels, generated by the `site`
/// repo's `npm run images` (`brand/logo-32.png`). Templates only ever scale
/// it by whole factors (`.pixel-art`), so its native size is part of the
/// contract (see the tests below). There is no raster wordmark: brand text is
/// rendered as text next to the mark.
const LOGO_ICON_PNG: &[u8] = include_bytes!("assets/impresspress-logo.png");
/// The same mark at 64x64 art-pixels (`brand/logo-64.png`) — served as the
/// `2x` `srcset` candidate so high-DPI screens get one device pixel per
/// art-pixel instead of a nearest-neighbour blow-up of the 32-cell mark.
const LOGO_ICON_2X_PNG: &[u8] = include_bytes!("assets/impresspress-logo-2x.png");
/// Impresspress favicon — bundled so every deployment ships its own `<link rel="icon">`
/// target without depending on a per-deployment external URL or the implicit
/// browser fallback to `/favicon.ico` (which 404s by default). Its 16/32/48
/// frames are 1:1 pixel-art renditions (`brand/favicon.ico`).
const FAVICON_ICO: &[u8] = include_bytes!("assets/favicon.ico");

/// The built-in brand accent, as a hex literal for surfaces that can't use
/// CSS variables (email inline styles). Must match `--primary-color` in
/// `assets/tokens.css` — the `brand_accent_matches_tokens_css` test pins the
/// two together so they can't drift.
pub const BRAND_ACCENT_HEX: &str = "#f0480f";

/// Impresspress square logo bytes.
pub fn logo_icon_png() -> &'static [u8] {
    LOGO_ICON_PNG
}

/// Impresspress square logo bytes at 2x (64x64 art-pixels).
pub fn logo_icon_2x_png() -> &'static [u8] {
    LOGO_ICON_2X_PNG
}

/// Square logo URL with content hash, e.g. `/b/static/impresspress-logo-a1b2c3d4.png`.
pub fn logo_icon_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| {
        format!(
            "{STATIC_PREFIX}impresspress-logo-{}.png",
            short_hash(LOGO_ICON_PNG)
        )
    })
}

/// 2x square logo URL with content hash, e.g. `/b/static/impresspress-logo-2x-a1b2c3d4.png`.
pub fn logo_icon_2x_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| {
        format!(
            "{STATIC_PREFIX}impresspress-logo-2x-{}.png",
            short_hash(LOGO_ICON_2X_PNG)
        )
    })
}

/// Impresspress favicon bytes.
pub fn favicon_ico() -> &'static [u8] {
    FAVICON_ICO
}

/// Favicon URL with content hash, e.g. `/b/static/favicon-a1b2c3d4.ico`.
pub fn favicon_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| format!("{STATIC_PREFIX}favicon-{}.ico", short_hash(FAVICON_ICO)))
}

/// Itim latin (basic) woff2 bytes.
pub fn itim_latin_woff2() -> &'static [u8] {
    ITIM_LATIN_WOFF2
}

/// Itim latin-ext woff2 bytes.
pub fn itim_latin_ext_woff2() -> &'static [u8] {
    ITIM_LATIN_EXT_WOFF2
}

/// Itim latin woff2 URL with content hash, e.g. `/b/static/itim-latin-a1b2c3d4.woff2`.
pub fn itim_latin_woff2_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| {
        format!(
            "{STATIC_PREFIX}itim-latin-{}.woff2",
            short_hash(ITIM_LATIN_WOFF2)
        )
    })
}

/// Itim latin-ext woff2 URL with content hash, e.g. `/b/static/itim-latin-ext-a1b2c3d4.woff2`.
pub fn itim_latin_ext_woff2_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| {
        format!(
            "{STATIC_PREFIX}itim-latin-ext-{}.woff2",
            short_hash(ITIM_LATIN_EXT_WOFF2)
        )
    })
}

/// Embedded CSS bundle — concatenation of tokens / base / components / layout.
/// Served as one file at the URL returned by `css_url()` so a single
/// `<link rel="stylesheet">` covers everything. The two font URL placeholders
/// in tokens.css are substituted with the content-hashed worker-bundled
/// URLs at bundle generation time.
///
/// Cached in a `OnceLock`: every CSS-bundle consumer (`css()`, `css_url()`,
/// and the static-asset handler) used to rebuild this on each call.
pub fn css_bundle() -> &'static str {
    static BUNDLE: OnceLock<String> = OnceLock::new();
    BUNDLE.get_or_init(|| {
        let tokens = TOKENS_CSS
            .replace("__ITIM_LATIN_URL__", itim_latin_woff2_url())
            .replace("__ITIM_LATIN_EXT_URL__", itim_latin_ext_woff2_url());
        format!("{tokens}\n{BASE_CSS}\n{COMPONENTS_CSS}\n{LAYOUT_CSS}\n{CHARTS_CSS}\n")
    })
}

/// The main CSS stylesheet (all design system styles combined).
pub fn css() -> &'static str {
    css_bundle()
}

/// htmx 2.x minified JS.
pub fn htmx_js() -> &'static str {
    include_str!("assets/htmx.min.js")
}

/// WebMCP tool-registration script, served on every page. Fetches the
/// auth-filtered manifest at `/b/webmcp/manifest.json` and registers each
/// tool via `document.modelContext.registerTool` (no-ops on browsers
/// without WebMCP support). On a service-worker build the first fetch waits
/// for the worker to take control of the page (see `assets/webmcp.js`);
/// `window.__impresspressWebmcp.refresh()` re-fetches the manifest and swaps
/// out whatever this script previously registered.
///
/// Composed at first use from [`WEBMCP_CORE`] (the `buildRequest`/
/// `toolOptions` fragment) and `assets/webmcp.js` (the tail), via
/// [`compose_webmcp_script`] — cached so repeat callers don't re-format the
/// string.
pub fn webmcp_js() -> &'static str {
    static SCRIPT: LazyLock<String> =
        LazyLock::new(|| compose_webmcp_script(include_str!("assets/webmcp.js")));
    &SCRIPT
}

/// Short content hash (first 8 chars of hex SHA-256) for cache busting.
fn short_hash(content: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let hash = Sha256::digest(content);
    hash.iter().take(4).map(|b| format!("{b:02x}")).collect()
}

/// CSS URL with content hash, e.g. `/b/static/app-a1b2c3d4.css`
pub fn css_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| format!("{STATIC_PREFIX}app-{}.css", short_hash(css().as_bytes())))
}

/// htmx JS URL with content hash, e.g. `/b/static/htmx-a1b2c3d4.min.js`
pub fn htmx_js_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| {
        format!(
            "{STATIC_PREFIX}htmx-{}.min.js",
            short_hash(htmx_js().as_bytes())
        )
    })
}

/// Short content hash of [`webmcp_js`] — the same hash embedded in
/// [`webmcp_js_url`] and, at the stable path, exposed as the `ETag` of
/// `GET /b/webmcp/webmcp.js` (`pipeline.rs`). One function so the two
/// projections of "which version of the script is this" can never drift
/// apart.
pub fn webmcp_js_hash() -> &'static str {
    static HASH: OnceLock<String> = OnceLock::new();
    HASH.get_or_init(|| short_hash(webmcp_js().as_bytes()))
}

/// WebMCP script URL with content hash, e.g. `/b/static/webmcp-a1b2c3d4.js`
pub fn webmcp_js_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| format!("{STATIC_PREFIX}webmcp-{}.js", webmcp_js_hash()))
}

/// Stable (non-content-hashed) path for `webmcp.js`, served by
/// `pipeline.rs` at `GET /b/webmcp/webmcp.js` — right beside
/// `/b/webmcp/manifest.json`. Unlike [`webmcp_js_url`], this path never
/// changes between deploys, so it's the one an agent-written page under
/// `site/` (served by `wafer-run/web`, not `SystemBlock`'s content-hashed
/// `/b/static/*` table) can hardcode in a `<script>` tag without first
/// discovering the current hash.
pub const WEBMCP_JS_STABLE_PATH: &str = "/b/webmcp/webmcp.js";

/// marked.js (markdown parser), vendored from marked@14 — self-hosted instead of
/// a jsdelivr CDN `<script>` so there's no external runtime fetch (CSP-friendly,
/// no third-party availability/supply-chain dependency at page load).
///
/// Only consumed by the LLM chat page (`blocks::llm::pages`), which is itself
/// gated behind `block-llm` — feature-gated here too so a build without the
/// LLM block (e.g. Cloudflare, which can't enable `block-llm`: the provider
/// service isn't wasm32-compatible) doesn't embed this JS.
#[cfg(feature = "block-llm")]
pub fn marked_js() -> &'static str {
    include_str!("assets/marked.min.js")
}

/// marked.js URL with content hash, e.g. `/b/static/marked-a1b2c3d4.min.js`
#[cfg(feature = "block-llm")]
pub fn marked_js_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| {
        format!(
            "{STATIC_PREFIX}marked-{}.min.js",
            short_hash(marked_js().as_bytes())
        )
    })
}

/// DOMPurify (HTML sanitizer), vendored from DOMPurify 3.2.4 — self-hosted
/// instead of a CDN `<script>` so there's no external runtime fetch
/// (CSP-friendly, no third-party availability/supply-chain dependency at
/// page load). Loaded before `marked.js`/`llm-chat.js` so `renderMarkdown`
/// can sanitize the parsed markdown before it reaches `innerHTML`
/// (P0 stored-XSS fix).
///
/// Like `marked_js`, only the LLM chat page loads this — gated behind
/// `block-llm` for the same reason.
#[cfg(feature = "block-llm")]
const PURIFY_JS: &str = include_str!("assets/purify.min.js");

#[cfg(feature = "block-llm")]
pub fn purify_js() -> &'static str {
    PURIFY_JS
}

/// DOMPurify JS URL with content hash, e.g. `/b/static/purify-a1b2c3d4.js`
#[cfg(feature = "block-llm")]
pub fn purify_js_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| {
        format!(
            "{STATIC_PREFIX}purify-{}.js",
            short_hash(purify_js().as_bytes())
        )
    })
}

/// Embedded vanilla-JS bundle for the LLM chat surface — markdown, message
/// rendering, model management, chat submission, thread creation/selection.
/// Consumed by the unified LLM page handler and (for the conversation lens)
/// by the Messages context_detail handler.
///
/// Gated behind `block-llm`: Cloudflare currently cannot enable `block-llm`
/// (the provider service isn't wasm32-compatible), so this JS has no
/// consumer there — embedding it unconditionally was pure bloat.
#[cfg(feature = "block-llm")]
const LLM_CHAT_JS: &str = include_str!("assets/llm-chat.js");

#[cfg(feature = "block-llm")]
pub fn llm_chat_js() -> &'static str {
    LLM_CHAT_JS
}

/// LLM chat JS URL with content hash, e.g. `/b/static/llm-chat-a1b2c3d4.js`.
/// Not minified — readability matters for a script that's debugged in
/// Chrome devtools.
#[cfg(feature = "block-llm")]
pub fn llm_chat_js_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| {
        format!(
            "{STATIC_PREFIX}llm-chat-{}.js",
            short_hash(llm_chat_js().as_bytes())
        )
    })
}

/// Embedded vanilla-JS bundle for the file-browser surfaces — drag-drop
/// upload, bulk select, kebab menus, share modal, upload modal,
/// confirm-delete. Consumed by `pages_user::object_list_page` and
/// `cloudstorage_page`, both in the `block-files`-gated `blocks::files`
/// module — gated here to match, so a build without the Files block drops
/// this JS too.
#[cfg(feature = "block-files")]
const FILES_BROWSER_JS: &str = include_str!("assets/files-browser.js");

#[cfg(feature = "block-files")]
pub fn files_browser_js() -> &'static str {
    FILES_BROWSER_JS
}

/// Files-browser JS URL with content hash, e.g. `/b/static/files-browser-a1b2c3d4.js`.
#[cfg(feature = "block-files")]
pub fn files_browser_js_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| {
        format!(
            "{STATIC_PREFIX}files-browser-{}.js",
            short_hash(files_browser_js().as_bytes())
        )
    })
}

/// Small inline JS for toast notifications (triggered by htmx HX-Trigger).
pub fn toast_js() -> &'static str {
    r#"
document.body.addEventListener("showToast", function(e) {
    var d = e.detail || {};
    var c = document.getElementById("toast-container");
    if (!c) return;
    var t = document.createElement("div");
    var kind = ["success", "error", "warning", "info"].indexOf(d.type) >= 0 ? d.type : "info";
    t.className = "toast toast-" + kind;
    var message = document.createElement("span");
    message.textContent = String(d.message || "");
    var dismiss = document.createElement("button");
    dismiss.className = "toast-dismiss";
    dismiss.type = "button";
    dismiss.setAttribute("aria-label", "Dismiss");
    dismiss.textContent = "×";
    dismiss.addEventListener("click", function() { t.remove(); });
    t.appendChild(message);
    t.appendChild(dismiss);
    c.appendChild(t);
    setTimeout(function() { t.remove(); }, 4000);
});
"#
}

/// Vanilla JS for the command palette — open/close, fuzzy filter,
/// keyboard navigation. Embedded as a string the same way `toast_js()`
/// and `modal_js()` are.
pub fn palette_js() -> &'static str {
    r#"
(function () {
  if (window.__cmdkInit) return;
  window.__cmdkInit = true;
  const el = document.getElementById('cmdk');
  if (!el) return;
  const input = document.getElementById('cmdk-input');
  const list = document.getElementById('cmdk-list');

  const items = () => Array.from(list.querySelectorAll('.palette__item'));
  let selected = 0;

  function open() {
    el.dataset.open = 'true';
    el.setAttribute('aria-hidden', 'false');
    input.value = '';
    apply('');
    requestAnimationFrame(() => input.focus());
  }
  function close() {
    el.dataset.open = 'false';
    el.setAttribute('aria-hidden', 'true');
  }
  function visibleItems() { return items().filter(i => !i.classList.contains('is-hidden')); }

  function apply(query) {
    const q = query.trim().toLowerCase();
    items().forEach(i => {
      const k = (i.dataset.keywords || '').toLowerCase();
      const match = !q || k.includes(q);
      i.classList.toggle('is-hidden', !match);
      i.setAttribute('aria-selected', 'false');
    });
    const vis = visibleItems();
    selected = 0;
    if (vis[0]) vis[0].setAttribute('aria-selected', 'true');
  }

  function move(delta) {
    const vis = visibleItems();
    if (!vis.length) return;
    vis[selected]?.setAttribute('aria-selected', 'false');
    selected = (selected + delta + vis.length) % vis.length;
    vis[selected].setAttribute('aria-selected', 'true');
    vis[selected].scrollIntoView({ block: 'nearest' });
  }

  function activate() {
    const vis = visibleItems();
    const sel = vis[selected];
    if (!sel?.dataset.href) return;
    if (sel.dataset.external === 'true') {
      window.open(sel.dataset.href, '_blank', 'noopener,noreferrer');
    } else {
      window.location.assign(sel.dataset.href);
    }
  }

  // Hotkeys
  document.addEventListener('keydown', (e) => {
    const isMod = e.metaKey || e.ctrlKey;
    if (isMod && e.key.toLowerCase() === 'k') { e.preventDefault(); open(); return; }
    if (el.dataset.open !== 'true') return;
    if (e.key === 'Escape') { e.preventDefault(); close(); }
    else if (e.key === 'ArrowDown') { e.preventDefault(); move(1); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); move(-1); }
    else if (e.key === 'Enter') { e.preventDefault(); activate(); }
  });

  // Click triggers
  document.addEventListener('click', (e) => {
    const t = e.target.closest('[data-action]');
    if (!t) return;
    if (t.dataset.action === 'palette-open') { e.preventDefault(); open(); }
    if (t.dataset.action === 'palette-close') { e.preventDefault(); close(); }
  });

  // The shortcut hint defaults to the Mac glyph; swap to Ctrl elsewhere so
  // the advertised key matches what the keydown handler above accepts.
  if (!/Mac|iPhone|iPad|iPod/.test(navigator.platform || '')) {
    document.querySelectorAll('.topbar__palette-cmd').forEach((n) => { n.textContent = 'Ctrl'; });
    document.querySelectorAll('.shell__palette-icon').forEach((n) => { n.textContent = 'Ctrl K'; });
  }

  // Linked table rows (`.data-table__row--linked`) style as clickable; make
  // the whole row actually navigate via its row-href anchor, unless the
  // click landed on an interactive element of its own.
  document.addEventListener('click', (e) => {
    const row = e.target.closest('.data-table__row--linked');
    if (!row || e.target.closest('a, button, input, select, label, textarea')) return;
    const anchor = row.querySelector('.data-table__row-href a');
    if (anchor) anchor.click();
  });

  // Item click → navigate
  list.addEventListener('click', (e) => {
    const item = e.target.closest('.palette__item');
    if (!item?.dataset.href) return;
    if (item.dataset.external === 'true') {
      window.open(item.dataset.href, '_blank', 'noopener,noreferrer');
    } else {
      window.location.assign(item.dataset.href);
    }
  });

  input.addEventListener('input', (e) => apply(e.target.value));

  // Keyboard scrolling for the app shell. The document never scrolls (the
  // .shell grid is 100vh; .shell__body is the real scroller), so with no
  // focused element PageDown/PageUp/Space/Home/End/arrows would silently do
  // nothing. Registered after the palette handler above, so an open palette
  // (which preventDefaults its own keys) wins. Only fires when the event
  // target is the page itself — typing in fields and focused widgets keep
  // their native behavior.
  document.addEventListener('keydown', (e) => {
    if (e.defaultPrevented || e.metaKey || e.ctrlKey || e.altKey) return;
    if (e.target !== document.body && e.target !== document.documentElement) return;
    const scroller = document.querySelector('.shell__body');
    if (!scroller) return;
    const pageStep = scroller.clientHeight * 0.9;
    const lineStep = 40;
    let dy;
    switch (e.key) {
      case 'PageDown': dy = pageStep; break;
      case 'PageUp': dy = -pageStep; break;
      case ' ': dy = e.shiftKey ? -pageStep : pageStep; break;
      case 'ArrowDown': dy = lineStep; break;
      case 'ArrowUp': dy = -lineStep; break;
      case 'Home': scroller.scrollTo({ top: 0 }); e.preventDefault(); return;
      case 'End': scroller.scrollTo({ top: scroller.scrollHeight }); e.preventDefault(); return;
      default: return;
    }
    scroller.scrollBy({ top: dy });
    e.preventDefault();
  });
})();
"#
}

/// Small inline JS for modal close (Escape key + overlay click).
pub fn modal_js() -> &'static str {
    r#"
document.addEventListener("keydown", function(e) {
    if (e.key === "Escape") {
        var m = document.querySelector('.modal-overlay:not([hidden])');
        if (m) m.setAttribute("hidden", "");
    }
});
function openModal(id) {
    var m = document.getElementById(id);
    if (m) m.removeAttribute("hidden");
}
function closeModal(id) {
    var m = document.getElementById(id);
    if (m) m.setAttribute("hidden", "");
}
document.body.addEventListener("closeModal", function(e) {
    var d = e.detail || {};
    if (d.id) closeModal(d.id);
});
"#
}

/// Vanilla JS for the mobile sidebar drawer. Toggles `body[data-drawer-open]`
/// from clicks on `[data-action="drawer-open"]` (the hamburger), the overlay
/// (`[data-action="drawer-close"]`), Escape, or any sidebar nav-link click
/// (so navigation auto-collapses the drawer).
pub fn drawer_js() -> &'static str {
    r#"
(function () {
  if (window.__drawerInit) return;
  window.__drawerInit = true;
  var body = document.body;
  function open() { body.setAttribute('data-drawer-open', 'true'); }
  function close() { body.removeAttribute('data-drawer-open'); }
  document.addEventListener('click', function (e) {
    var t = e.target;
    if (!(t instanceof Element)) return;
    var actEl = t.closest('[data-action]');
    var action = actEl ? actEl.getAttribute('data-action') : null;
    if (action === 'drawer-open') { open(); e.preventDefault(); return; }
    if (action === 'drawer-close') { close(); e.preventDefault(); return; }
    if (body.hasAttribute('data-drawer-open') && t.closest('.sidebar a')) {
      close();
    }
  });
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape' && body.hasAttribute('data-drawer-open')) {
      close();
    }
  });
})();
"#
}

#[cfg(test)]
mod tests {
    #[test]
    fn toast_messages_are_rendered_as_text_not_html() {
        let js = super::toast_js();
        assert!(
            !js.contains("innerHTML"),
            "toast content must not use an HTML sink"
        );
        assert!(js.contains("message.textContent"));
        assert!(js.contains("createElement(\"button\")"));
        assert!(js.contains("addEventListener(\"click\""));
    }

    #[test]
    fn css_bundle_includes_all_layers() {
        let s = super::css_bundle();
        assert!(s.contains("--primary-color"), "tokens layer missing");
        assert!(s.contains("box-sizing"), "base layer missing");
        assert!(
            s.contains(".btn") || s.contains(".button"),
            "components layer missing"
        );
        assert!(s.contains(".shell"), "layout layer missing");
    }

    #[test]
    fn brand_accent_matches_tokens_css() {
        // BRAND_ACCENT_HEX exists for CSS-var-less surfaces (emails). It must
        // stay byte-identical to the stylesheet's --primary-color default.
        assert!(
            super::TOKENS_CSS.contains(&format!("--primary-color: {}", super::BRAND_ACCENT_HEX)),
            "BRAND_ACCENT_HEX ({}) does not match --primary-color in tokens.css",
            super::BRAND_ACCENT_HEX
        );
    }

    #[test]
    fn css_bundle_substitutes_itim_font_urls() {
        let s = super::css_bundle();
        // No raw placeholders left in the served bundle.
        assert!(
            !s.contains("__ITIM_LATIN_URL__"),
            "tokens.css placeholder __ITIM_LATIN_URL__ not substituted"
        );
        assert!(
            !s.contains("__ITIM_LATIN_EXT_URL__"),
            "tokens.css placeholder __ITIM_LATIN_EXT_URL__ not substituted"
        );
        // No reference to the old hardcoded external host.
        assert!(
            !s.contains("impresspress.org/fonts/"),
            "stale impresspress.org font URL still in bundle"
        );
        // The hashed worker-bundled URLs are present.
        assert!(
            s.contains(super::itim_latin_woff2_url()),
            "itim-latin URL missing from bundle"
        );
        assert!(
            s.contains(super::itim_latin_ext_woff2_url()),
            "itim-latin-ext URL missing from bundle"
        );
    }

    #[test]
    fn itim_font_urls_have_content_hash() {
        for url in [
            super::itim_latin_woff2_url(),
            super::itim_latin_ext_woff2_url(),
        ] {
            assert!(url.starts_with("/b/static/itim-latin"));
            assert!(url.ends_with(".woff2"));
        }
    }

    /// PNG width/height from the IHDR chunk (big-endian u32 at bytes 16/20).
    fn png_size(png: &[u8]) -> (u32, u32) {
        assert_eq!(&png[1..4], b"PNG", "not a PNG");
        let be = |i: usize| u32::from_be_bytes([png[i], png[i + 1], png[i + 2], png[i + 3]]);
        (be(16), be(20))
    }

    // The brand art is real pixel art (generated in the `site` repo's
    // `brand/` kit) and the templates scale it only by whole factors, so
    // the native sizes are part of the contract.
    #[test]
    fn logo_icon_png_is_the_32_cell_mark() {
        assert_eq!(png_size(super::logo_icon_png()), (32, 32));
    }

    #[test]
    fn logo_icon_2x_png_is_the_64_cell_mark() {
        assert_eq!(png_size(super::logo_icon_2x_png()), (64, 64));
    }

    #[test]
    fn logo_icon_2x_url_has_content_hash() {
        let url = super::logo_icon_2x_url();
        assert!(url.starts_with("/b/static/impresspress-logo-2x-"), "{url}");
        assert!(url.ends_with(".png"));
        let hash = url
            .trim_start_matches("/b/static/impresspress-logo-2x-")
            .trim_end_matches(".png");
        assert_eq!(hash.len(), 8, "expected 8-char short hash, got: {hash}");
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn favicon_ico_frames_are_16_32_48_at_native_size() {
        let ico = super::favicon_ico();
        assert_eq!(u16::from_le_bytes([ico[2], ico[3]]), 1, "ICO type");
        let count = u16::from_le_bytes([ico[4], ico[5]]) as usize;
        let sizes: Vec<u8> = (0..count).map(|i| ico[6 + i * 16]).collect();
        assert_eq!(sizes, vec![16, 32, 48]);
        for (i, &size) in sizes.iter().enumerate() {
            let e = 6 + i * 16;
            let len =
                u32::from_le_bytes([ico[e + 8], ico[e + 9], ico[e + 10], ico[e + 11]]) as usize;
            let off =
                u32::from_le_bytes([ico[e + 12], ico[e + 13], ico[e + 14], ico[e + 15]]) as usize;
            let frame = &ico[off..off + len];
            assert_eq!(
                png_size(frame),
                (u32::from(size), u32::from(size)),
                "frame {i} is a 1:1 PNG"
            );
        }
    }

    #[test]
    fn favicon_url_has_content_hash() {
        let url = super::favicon_url();
        assert!(url.starts_with("/b/static/favicon-"));
        assert!(url.ends_with(".ico"));
        let hash = url
            .trim_start_matches("/b/static/favicon-")
            .trim_end_matches(".ico");
        assert_eq!(hash.len(), 8, "expected 8-char short hash, got: {hash}");
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn tokens_include_new_scale() {
        let s = super::css_bundle();
        for tok in [
            "--text-base",
            "--text-2xl",
            "--space-2xl",
            "--surface-1",
            "--primary-button",
            "--focus-ring",
        ] {
            assert!(s.contains(tok), "missing token: {tok}");
        }
    }

    #[test]
    fn palette_js_present_and_self_invoking() {
        let js = super::palette_js();
        assert!(js.contains("cmdk"));
        assert!(js.contains("Meta+K") || js.contains("metaKey"));
        assert!(js.starts_with("\n(function") || js.contains("(function "));
    }

    #[test]
    fn drawer_js_handles_open_close_esc_and_navlink() {
        let js = super::drawer_js();
        assert!(js.contains("'drawer-open'"));
        assert!(js.contains("'drawer-close'"));
        assert!(js.contains("'Escape'"));
        assert!(js.contains(".sidebar a"));
        assert!(js.contains("data-drawer-open"));
        // Self-invoking + idempotent guard.
        assert!(js.contains("__drawerInit"));
    }

    #[test]
    fn webmcp_js_composes_the_core_fragment_into_one_iife() {
        let js = super::webmcp_js();
        assert!(
            js.starts_with("(function () {\n  'use strict';"),
            "composed script must start with the IIFE: {js}"
        );
        assert!(
            js.contains("function buildRequest"),
            "core fragment's buildRequest is missing"
        );
        assert!(
            js.contains("function toolOptions"),
            "core fragment's toolOptions is missing"
        );
        assert!(
            js.contains("__impresspressWebmcp"),
            "tail's window.__impresspressWebmcp is missing"
        );
        assert!(
            js.trim_end().ends_with("})();"),
            "composed script must end with the IIFE close: {js}"
        );
    }

    #[test]
    #[cfg(feature = "block-llm")]
    fn llm_chat_js_is_self_invoking_and_exposes_init() {
        let js = super::llm_chat_js();
        assert!(js.contains("(function ()") || js.contains("(function()"));
        assert!(js.contains("__impresspressLlmChatLoaded"));
        assert!(js.contains("window.impresspressLlmChat = { init: init }"));
        for sym in [
            "handleChatSubmit",
            "createNewThread",
            "selectThread",
            "onModelChange",
            "unloadLocalModel",
        ] {
            assert!(
                js.contains(&format!("window.{sym} = {sym}")),
                "missing global re-export for {sym}"
            );
        }
    }

    #[test]
    #[cfg(feature = "block-llm")]
    fn purify_js_url_has_content_hash() {
        let url = super::purify_js_url();
        assert!(url.starts_with("/b/static/purify-"));
        assert!(url.ends_with(".js"));
        let hash = url
            .trim_start_matches("/b/static/purify-")
            .trim_end_matches(".js");
        assert_eq!(hash.len(), 8, "expected 8-char short hash, got: {hash}");
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    #[cfg(feature = "block-llm")]
    fn purify_js_is_dompurify_umd_build() {
        let js = super::purify_js();
        assert!(
            js.contains("DOMPurify"),
            "vendored asset should be DOMPurify"
        );
        // UMD build: `(e=...globalThis...||self).DOMPurify=t()` — assigns
        // onto the global object (`window` in a browser) when there's no
        // CommonJS/AMD module system, which is the load path llm-chat.js
        // relies on for the bare `DOMPurify` global.
        assert!(
            js.contains(").DOMPurify=t()"),
            "expected UMD build to assign a global .DOMPurify"
        );
    }

    #[test]
    #[cfg(feature = "block-files")]
    fn files_browser_js_exposes_init_and_handles_drag_drop() {
        let js = super::files_browser_js();
        assert!(
            js.contains("impresspressFilesBrowser"),
            "module namespace missing"
        );
        assert!(js.contains("dragenter"), "drag handler missing");
        assert!(js.contains("dragover"), "drag handler missing");
        assert!(
            js.contains("'drop'") || js.contains("\"drop\""),
            "drop handler missing"
        );
        assert!(js.contains("data-bulk-toggle"), "bulk-select missing");
        assert!(js.contains("data-action-menu"), "kebab handler missing");
        assert!(js.contains("dialog"), "modal uses <dialog>");
    }

    #[test]
    #[cfg(feature = "block-files")]
    fn files_browser_js_url_has_content_hash() {
        let url = super::files_browser_js_url();
        assert!(url.starts_with("/b/static/files-browser-"));
        assert!(url.ends_with(".js"));
        let hash = url
            .trim_start_matches("/b/static/files-browser-")
            .trim_end_matches(".js");
        assert_eq!(hash.len(), 8);
    }

    #[test]
    #[cfg(feature = "block-llm")]
    fn llm_chat_js_url_has_content_hash() {
        let url = super::llm_chat_js_url();
        assert!(url.starts_with("/b/static/llm-chat-"));
        assert!(url.ends_with(".js"));
        assert!(
            !url.ends_with(".min.js"),
            "we deliberately ship un-minified"
        );
        let mid = url
            .trim_start_matches("/b/static/llm-chat-")
            .trim_end_matches(".js");
        assert_eq!(mid.len(), 8, "expected 8-char short hash, got: {mid}");
        assert!(mid.chars().all(|c| c.is_ascii_hexdigit()));
    }
}
