import { test, expect, type Page } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { loginToWorkspace } from './fixtures/dev-sandbox';
import { MODEL_CONTEXT_POLYFILL } from './fixtures/model-context-polyfill';
import { execute, waitForTool, type ToolResult } from './fixtures/webmcp-helpers';

/**
 * `dev_compile_block` — the tool that turns Rust in the workspace into a
 * block serving at `/b/<name>/`.
 *
 * Everything below the tool is already covered elsewhere:
 * `dev-compiler.spec.ts` drives `BrowserRustCompiler` against the protocol and
 * proves the packaged worker is allowed to start at all, and
 * `dev-foundations.spec.ts` drives `POST /b/dev/api/builds/stage` with a
 * pre-built guest over `fetch`. What is left — and what is here — is the page
 * function that joins them: read `blocks/<name>/` out of the workspace, hand
 * it to the compiler, base64 the module it produced, stage it, and report the
 * result to whoever asked, whether that was an agent or the Compile button.
 *
 * # Why the worker is a fake and the artifact is not
 *
 * The real toolchain is 72 MiB and takes ~38 s to build the `hello` template
 * (`compiler/README.md`), which is Plan 3 Task 6's bill to pay, not this
 * file's. But the sixteen bytes `fixtures/fake-compiler-worker.js` normally
 * answers with would stop this test at the first thing it wants to prove:
 * staging INSTANTIATES the module, reads its `BlockInfo` and runs its
 * lifecycle before it will activate anything, so sixteen bytes are refused and
 * `/b/hello/` never exists.
 *
 * So the artifact is real and the compiler is not. The test scaffolds the
 * block through `dev_create_block`, reads the three files back out of the
 * workspace through `dev_read_file`, builds THOSE BYTES on the host with
 * `cargo build --release --target wasm32-wasip1`, and drops the module beside
 * the fake worker, which serves it as its own output. Everything the tool does
 * with that module — the base64, the source digest, the guest version, the
 * staging call, the validation, the runtime rebuild, the route that appears —
 * is the real thing running against a real `wasm32-wasip1` guest.
 *
 * # How the page is pointed at it
 *
 * `dev.js` reads one fixed URL for the compiler manifest
 * (`/__impresspress_dev/compiler/manifest.json`) and that is deliberate: which
 * toolchain a build carries is a property of the BUNDLE's asset overlay, not a
 * setting a page may be talked out of. So there is no override to reach for,
 * and the only honest way to hand the page a different toolchain is to change
 * what that URL answers. This spec therefore swaps the served manifest for one
 * naming the fake worker and puts the original bytes back afterwards. It is
 * safe because `playwright.config.ts` runs ONE worker with `fullyParallel:
 * false` — no other spec can be looking at that file while this one runs — and
 * because `dist/` is build output, regenerated by `build.sh`.
 */

/**
 * The bundle being served on `TEST_PORT`.
 *
 * CI exports `DEV_DIST` from `build.sh`'s last line; a local run defaults to
 * the same path that script writes to.
 */
const DEV_DIST =
  process.env.DEV_DIST ??
  fileURLToPath(new URL('../../../../examples/dev-sandbox/dist', import.meta.url));

/**
 * The fixture's own directory, deliberately NOT the `test/` one
 * `dev-compiler.spec.ts` uses: a real `hello.wasm` next to that worker would
 * change what its protocol assertions see (they pin the canned sixteen
 * bytes), and two specs sharing a directory would couple them through the
 * order they happen to run in.
 */
const TOOL_COMPILER_DIR = path.join(DEV_DIST, '__impresspress_dev', 'compiler', 'tool');
const TOOL_WORKER_URL = '/__impresspress_dev/compiler/tool/worker.js';

const FAKE_WORKER = fileURLToPath(new URL('./fixtures/fake-compiler-worker.js', import.meta.url));

/** The manifest `dev.js` reads, and the bytes `build.sh` put there. */
const REAL_MANIFEST_FILE = path.join(DEV_DIST, '__impresspress_dev', 'compiler', 'manifest.json');
let realManifest: Buffer;

/** What `fake-compiler-worker.js` answers `rustc --version` with. */
const FAKE_RUSTC_VERSION = 'rustc 1.90.0-nightly (fake worker)';

/** The block the test builds, and the one the `hello` template is written for. */
const BLOCK = 'hello';

/**
 * The block whose name makes the fake worker break its own protocol.
 *
 * `crateName` is the fake's only switch (it is the one field of a compile
 * message the page controls), and the block-name rule — lowercase letters,
 * digits and hyphens — admits this one, so a real scaffolded block can carry
 * it. Compiling it is how the adapter's "destroy the worker and reject" path
 * is reached through the TOOL rather than through the adapter's own API.
 */
const BROKEN = 'protocol-error';

/** What the `hello` template's one endpoint answers with, verbatim. */
const GREETING = 'Hello from site/hello — a block compiled in your browser.';

test.beforeAll(() => {
  mkdirSync(TOOL_COMPILER_DIR, { recursive: true });
  copyFileSync(FAKE_WORKER, path.join(TOOL_COMPILER_DIR, 'worker.js'));

  if (!existsSync(REAL_MANIFEST_FILE)) {
    throw new Error(
      `${REAL_MANIFEST_FILE} is missing: this bundle was built without the compiler overlay, ` +
        'so `/b/dev` would report "No compiler in this build" and nothing here could run. ' +
        'Rebuild with examples/dev-sandbox/build.sh.',
    );
  }
  realManifest = readFileSync(REAL_MANIFEST_FILE);
  // The same shape `scripts/write-manifest.mjs` writes, minus the asset
  // inventory nothing on the page reads: the adapter takes `entry`, `version`
  // and `target`, and refuses a manifest missing any of them.
  writeFileSync(
    REAL_MANIFEST_FILE,
    `${JSON.stringify(
      {
        schema_version: 1,
        version: 'test',
        entry: TOOL_WORKER_URL,
        total_bytes: 0,
        assets: [],
        license: 'MIT OR Apache-2.0',
        target: 'wasm32-wasip1',
      },
      null,
      2,
    )}\n`,
  );
});

test.afterAll(() => {
  // Byte for byte what `build.sh` produced. The fixture must not outlive the
  // run that needed it — least of all in a tree a deploy uploads.
  writeFileSync(REAL_MANIFEST_FILE, realManifest);
  rmSync(TOOL_COMPILER_DIR, { recursive: true, force: true });
});

/** The structured half of a tool result, with "and it was not an error" folded in. */
function structured<T>(result: ToolResult): T {
  expect(result.isError, result.content[0]?.text).toBeFalsy();
  expect(result.structuredContent, JSON.stringify(result)).toBeTruthy();
  return result.structuredContent as unknown as T;
}

type FileEntry = { path: string; sha256: string; size: number };
type FileRead = FileEntry & { encoding: string; content: string };
type CreateBlock = { name: string; files: FileEntry[] };
type Generation = { id: string; cause: string; status: string };
type Diagnostic = { severity: string; code: string; message: string; file: string | null };
type Compile = {
  success: boolean;
  build_id: string | null;
  generation: Generation | null;
  diagnostics: Diagnostic[];
  stdout: string;
  stderr: string;
  elapsed_ms: number;
  compiler_version: string | null;
  progress: Array<{ phase: string; ms: number }>;
};

/** What `GET /b/<name>/` answers right now, read from inside the document. */
async function fetchBlock(page: Page, name: string) {
  return page.evaluate(async (blockName) => {
    const response = await fetch(`/b/${blockName}/`);
    return { status: response.status, body: await response.text() };
  }, name);
}

test('dev_compile_block compiles a scaffolded block, stages it and puts it live; failures are results', async ({
  page,
}) => {
  // A cold boot compiles the wasm, creates the OPFS database, runs every
  // block's migrations and imports the seed; three activations then each
  // rebuild the wasmi runtime. The default 60 s is a boot budget.
  test.setTimeout(900_000);

  await page.addInitScript(MODEL_CONTEXT_POLYFILL);
  await loginToWorkspace(page);
  await waitForTool(page, 'dev_create_block');
  await waitForTool(page, 'dev_compile_block');

  // The page found the (substituted) manifest: the version line is written,
  // and the only thing still holding the button back is that the workspace has
  // no blocks yet. Without this the tool below would refuse with "No compiler
  // in this build." and every assertion after it would be about the wrong
  // thing.
  await expect(page.locator('#dev-compiler-version')).toHaveText(/^Compiler vtest /);
  await expect(page.locator('#dev-compile')).toBeDisabled();

  // --- 1. Scaffold, and build the very same bytes on the host -------------
  const created = structured<CreateBlock>(
    await execute(page, 'dev_create_block', { name: BLOCK, template: 'hello' }),
  );
  // …and now there is something to compile, so the button turns on. Both
  // halves of `updateCompileButton`, in the order a first-time visitor meets
  // them.
  await expect(page.locator('#dev-compile')).toBeEnabled();
  expect(created.files.map((f) => f.path)).toEqual([
    `blocks/${BLOCK}/Cargo.toml`,
    `blocks/${BLOCK}/src/lib.rs`,
    `blocks/${BLOCK}/src/wafer_guest.rs`,
  ]);

  // Read back through the tool an agent would use, not off the host's copy of
  // the templates: what gets compiled has to be what the WORKSPACE holds, or
  // this proves nothing about the round trip the sandbox actually makes.
  const crate = mkdtempSync(path.join(tmpdir(), 'dev-compile-'));
  for (const entry of created.files) {
    const file = structured<FileRead>(await execute(page, 'dev_read_file', { path: entry.path }));
    expect(file.encoding).toBe('utf8');
    const target = path.join(crate, entry.path.slice(`blocks/${BLOCK}/`.length));
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, file.content);
  }
  // `--offline` because a sandbox block has an empty `[dependencies]` by
  // construction (the browser toolchain has no registry access, so the whole
  // SDK is the vendored `src/wafer_guest.rs`) — a build that needed the
  // network here would mean the template had grown a dependency it cannot
  // have.
  execFileSync('cargo', ['build', '--release', '--target', 'wasm32-wasip1', '--offline'], {
    cwd: crate,
    stdio: 'inherit',
  });
  copyFileSync(
    path.join(crate, 'target', 'wasm32-wasip1', 'release', `${BLOCK}.wasm`),
    path.join(TOOL_COMPILER_DIR, `${BLOCK}.wasm`),
  );
  rmSync(crate, { recursive: true, force: true });

  // --- 2. Compile: the block is validated and live when the call returns ---
  const built = structured<Compile>(await execute(page, 'dev_compile_block', { name: BLOCK }));
  expect(built.success).toBe(true);
  expect(built.diagnostics).toEqual([]);
  expect(built.build_id).toBeTruthy();
  // `GenerationCause::BlockCompile`, in its serde spelling: the block set
  // changed, so this generation is not a site write.
  expect(built.generation?.cause).toBe('block_compile');
  expect(built.generation?.status).toBe('active');
  // `rustc --version` as the worker reported it at `ready` — the string the
  // build row records as `compiler_version`, not one the page made up.
  expect(built.compiler_version).toBe(FAKE_RUSTC_VERSION);
  // Every phase of `ActivationPhase`, in order: a new block means the runtime
  // was rebuilt, which is the step a site-only write skips.
  expect(built.progress.map((p) => p.phase)).toEqual([
    'validating',
    'building_runtime',
    'publishing',
    'active',
  ]);

  // The panel shows the activation that just landed, and still shows it after
  // the catch-up poll `withProgress` runs on the way out — the journal has
  // rested at `idle` by then, so a ladder drawn from the status alone would
  // have blanked here.
  await expect(page.locator('#dev-progress-steps')).toHaveAttribute('data-phase', 'active');
  await expect(page.locator('#dev-progress-steps li[data-state="done"]')).toHaveCount(4);
  await expect(page.locator('#dev-log')).toContainText(`compiled ${BLOCK} — generation`);

  // …and the route is live. This is the whole claim: Rust written in a
  // browser, compiled, validated and serving, without a server anywhere.
  expect(await fetchBlock(page, BLOCK)).toEqual({ status: 200, body: GREETING });

  // --- 3. An adapter that broke leaves a page that still compiles ---------
  //
  // The fake worker answers this crate with an out-of-band `error`, which the
  // adapter treats as "nothing this worker says can be trusted": it terminates
  // it and rejects. That is NOT a verdict on the block, so it reaches the
  // agent as `isError` rather than as a failed build.
  structured<CreateBlock>(await execute(page, 'dev_create_block', { name: BROKEN, template: 'hello' }));
  const broke = await execute(page, 'dev_compile_block', { name: BROKEN });
  expect(broke.isError).toBe(true);
  expect(broke.content[0].text).toContain('the compiler image is corrupt');
  expect(broke.structuredContent).toBeUndefined();
  // The previous generation is untouched by a compiler that fell over.
  expect((await fetchBlock(page, BLOCK)).status).toBe(200);

  // --- 4. The Compile button runs the same function, on a fresh worker -----
  //
  // Nothing re-initialises the compiler between the violation above and this
  // click: the adapter builds a new worker on demand, and the button is how a
  // human would find that out. It also exercises the select — populated from
  // the `blocks/<name>/` prefixes in the file listing, which now has two.
  await expect(page.locator('#dev-compile-block option')).toHaveCount(2);
  await page.locator('#dev-compile-block').selectOption(BLOCK);
  // A NEW generation is the proof, not a log line: the panel already carries
  // one from step 2, so `#dev-log` alone would be satisfied by a button that
  // did nothing at all. Read without `structured`, because a poll's callback
  // must return a value rather than raise its own assertions.
  const activeGeneration = async () => {
    const result = await execute(page, 'dev_status', {});
    return (result.structuredContent as { active_generation: Generation | null })?.active_generation
      ?.id;
  };
  const before = await activeGeneration();
  expect(before).toBeTruthy();
  await page.locator('#dev-compile').click();
  await expect.poll(activeGeneration, { timeout: 120_000 }).not.toBe(before);
  expect(await fetchBlock(page, BLOCK)).toEqual({ status: 200, body: GREETING });

  // --- 5. A crate that does not compile is an ANSWER ----------------------
  const source = structured<FileRead>(
    await execute(page, 'dev_read_file', { path: `blocks/${BLOCK}/src/lib.rs` }),
  );
  structured(
    await execute(page, 'dev_write_file', {
      path: `blocks/${BLOCK}/src/lib.rs`,
      content: `${source.content}\nFAIL`,
      expected_sha256: source.sha256,
    }),
  );
  const failed = structured<Compile>(await execute(page, 'dev_compile_block', { name: BLOCK }));
  expect(failed.success).toBe(false);
  // No build row and no generation: nothing was staged, because nothing
  // compiled.
  expect(failed.build_id).toBeNull();
  expect(failed.generation).toBeNull();
  expect(failed.diagnostics[0]).toMatchObject({ file: 'src/lib.rs', severity: 'error' });
  // …and the block that WAS compiled is still serving. A failed compile is not
  // a deployment.
  expect(await fetchBlock(page, BLOCK)).toEqual({ status: 200, body: GREETING });
});
